//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingbsform.Model
{
    using Dapper.Contrib.Extensions;
    using System;
    using System.Collections.Generic;

    [Table("[Cart]")]
    public partial class Cart
    {
        [ExplicitKey]
        public string Id { get; set; }
        public string userid { get; set; }
        public string bookid { get; set; }
    }
}