//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingbsform.Model
{
    using Dapper.Contrib.Extensions;
    using System;
    using System.Collections.Generic;

    [Table("[Feedback]")]
    public partial class Feedback
    {
        [ExplicitKey]
        public string Id { get; set; }
        public string Userid { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Reply { get; set; }

        public FeedBackState State { get; set; }
    }

    public enum FeedBackState
    {
        UnReplay,
        Replaied,
        UserConfirm
    }
}
