//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingbsform.Model
{
    using Dapper.Contrib.Extensions;
    using System;
    using System.Collections.Generic;
    
    [Table("[User]")]
    public partial class User
    {
        [ExplicitKey]
        public string Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string telphone { get; set; }
        public string address { get; set; }
        public int type { get; set; }
    }
}
